import type { INodeProperties } from 'n8n-workflow';
import { multiOptionsToRepeatedParams } from '../../shared/utils';

const showOnlyForSeriesSearch = {
	operation: ['search'],
	resource: ['series'],
};

export const seriesSearchDescription: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'q',
		type: 'string',
		default: '',
		displayOptions: {
			show: showOnlyForSeriesSearch,
		},
		description: 'Search query for series title',
		routing: {
			send: {
				type: 'query',
				property: 'q',
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: showOnlyForSeriesSearch,
		},
		options: [
			{
				displayName: 'Content Rating',
				name: 'content_rating',
				type: 'multiOptions',
				default: ['safe', 'suggestive'],
				description: 'Filter by content rating',
				options: [
					{ name: 'Erotica', value: 'erotica' },
					{ name: 'Pornographic', value: 'pornographic' },
					{ name: 'Safe', value: 'safe' },
					{ name: 'Suggestive', value: 'suggestive' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('content_rating')],
					},
				},
			},
			{
				displayName: 'Exclude Content Rating',
				name: 'not_content_rating',
				type: 'multiOptions',
				default: [],
				description: 'Exclude content ratings',
				options: [
					{ name: 'Erotica', value: 'erotica' },
					{ name: 'Pornographic', value: 'pornographic' },
					{ name: 'Safe', value: 'safe' },
					{ name: 'Suggestive', value: 'suggestive' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('not_content_rating')],
					},
				},
			},
			{
				displayName: 'Exclude Genre',
				name: 'genre_not',
				type: 'multiOptions',
				default: [],
				description: 'Exclude genres',
				options: [
					{ name: 'Action', value: 'action' },
					{ name: 'Adult', value: 'adult' },
					{ name: 'Adventure', value: 'adventure' },
					{ name: 'Avant Garde', value: 'avant_garde' },
					{ name: 'Award Winning', value: 'award_winning' },
					{ name: 'Boys Love', value: 'boys_love' },
					{ name: 'Comedy', value: 'comedy' },
					{ name: 'Doujinshi', value: 'doujinshi' },
					{ name: 'Drama', value: 'drama' },
					{ name: 'Ecchi', value: 'ecchi' },
					{ name: 'Erotica', value: 'erotica' },
					{ name: 'Fantasy', value: 'fantasy' },
					{ name: 'Gender Bender', value: 'gender_bender' },
					{ name: 'Girls Love', value: 'girls_love' },
					{ name: 'Gourmet', value: 'gourmet' },
					{ name: 'Harem', value: 'harem' },
					{ name: 'Hentai', value: 'hentai' },
					{ name: 'Historical', value: 'historical' },
					{ name: 'Horror', value: 'horror' },
					{ name: 'Josei', value: 'josei' },
					{ name: 'Lolicon', value: 'lolicon' },
					{ name: 'Mahou Shoujo', value: 'mahou_shoujo' },
					{ name: 'Martial Arts', value: 'martial_arts' },
					{ name: 'Mature', value: 'mature' },
					{ name: 'Mecha', value: 'mecha' },
					{ name: 'Music', value: 'music' },
					{ name: 'Mystery', value: 'mystery' },
					{ name: 'Psychological', value: 'psychological' },
					{ name: 'Romance', value: 'romance' },
					{ name: 'School Life', value: 'school_life' },
					{ name: 'Sci-Fi', value: 'sci-fi' },
					{ name: 'Seinen', value: 'seinen' },
					{ name: 'Shotacon', value: 'shotacon' },
					{ name: 'Shoujo', value: 'shoujo' },
					{ name: 'Shoujo Ai', value: 'shoujo_ai' },
					{ name: 'Shounen', value: 'shounen' },
					{ name: 'Shounen Ai', value: 'shounen_ai' },
					{ name: 'Slice of Life', value: 'slice_of_life' },
					{ name: 'Smut', value: 'smut' },
					{ name: 'Sports', value: 'sports' },
					{ name: 'Supernatural', value: 'supernatural' },
					{ name: 'Suspense', value: 'suspense' },
					{ name: 'Thriller', value: 'thriller' },
					{ name: 'Tragedy', value: 'tragedy' },
					{ name: 'Yaoi', value: 'yaoi' },
					{ name: 'Yuri', value: 'yuri' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('genre_not')],
					},
				},
			},
			{
				displayName: 'Exclude Status',
				name: 'status_not',
				type: 'multiOptions',
				default: [],
				description: 'Exclude publication statuses',
				options: [
					{ name: 'Cancelled', value: 'cancelled' },
					{ name: 'Completed', value: 'completed' },
					{ name: 'Hiatus', value: 'hiatus' },
					{ name: 'Releasing', value: 'releasing' },
					{ name: 'Unknown', value: 'unknown' },
					{ name: 'Upcoming', value: 'upcoming' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('status_not')],
					},
				},
			},
			{
				displayName: 'Exclude Type',
				name: 'type_not',
				type: 'multiOptions',
				default: [],
				description: 'Exclude media types',
				options: [
					{ name: 'Manga', value: 'manga' },
					{ name: 'Manhua', value: 'manhua' },
					{ name: 'Manhwa', value: 'manhwa' },
					{ name: 'Novel', value: 'novel' },
					{ name: 'OEL', value: 'oel' },
					{ name: 'Other', value: 'other' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('type_not')],
					},
				},
			},
			{
				displayName: 'Genre',
				name: 'genre',
				type: 'multiOptions',
				default: [],
				description: 'Filter by genres',
				options: [
					{ name: 'Action', value: 'action' },
					{ name: 'Adult', value: 'adult' },
					{ name: 'Adventure', value: 'adventure' },
					{ name: 'Avant Garde', value: 'avant_garde' },
					{ name: 'Award Winning', value: 'award_winning' },
					{ name: 'Boys Love', value: 'boys_love' },
					{ name: 'Comedy', value: 'comedy' },
					{ name: 'Doujinshi', value: 'doujinshi' },
					{ name: 'Drama', value: 'drama' },
					{ name: 'Ecchi', value: 'ecchi' },
					{ name: 'Erotica', value: 'erotica' },
					{ name: 'Fantasy', value: 'fantasy' },
					{ name: 'Gender Bender', value: 'gender_bender' },
					{ name: 'Girls Love', value: 'girls_love' },
					{ name: 'Gourmet', value: 'gourmet' },
					{ name: 'Harem', value: 'harem' },
					{ name: 'Hentai', value: 'hentai' },
					{ name: 'Historical', value: 'historical' },
					{ name: 'Horror', value: 'horror' },
					{ name: 'Josei', value: 'josei' },
					{ name: 'Lolicon', value: 'lolicon' },
					{ name: 'Mahou Shoujo', value: 'mahou_shoujo' },
					{ name: 'Martial Arts', value: 'martial_arts' },
					{ name: 'Mature', value: 'mature' },
					{ name: 'Mecha', value: 'mecha' },
					{ name: 'Music', value: 'music' },
					{ name: 'Mystery', value: 'mystery' },
					{ name: 'Psychological', value: 'psychological' },
					{ name: 'Romance', value: 'romance' },
					{ name: 'School Life', value: 'school_life' },
					{ name: 'Sci-Fi', value: 'sci-fi' },
					{ name: 'Seinen', value: 'seinen' },
					{ name: 'Shotacon', value: 'shotacon' },
					{ name: 'Shoujo', value: 'shoujo' },
					{ name: 'Shoujo Ai', value: 'shoujo_ai' },
					{ name: 'Shounen', value: 'shounen' },
					{ name: 'Shounen Ai', value: 'shounen_ai' },
					{ name: 'Slice of Life', value: 'slice_of_life' },
					{ name: 'Smut', value: 'smut' },
					{ name: 'Sports', value: 'sports' },
					{ name: 'Supernatural', value: 'supernatural' },
					{ name: 'Suspense', value: 'suspense' },
					{ name: 'Thriller', value: 'thriller' },
					{ name: 'Tragedy', value: 'tragedy' },
					{ name: 'Yaoi', value: 'yaoi' },
					{ name: 'Yuri', value: 'yuri' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('genre')],
					},
				},
			},
			{
				displayName: 'Is Licensed',
				name: 'is_licensed',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by licensed state',
				routing: {
					send: {
						type: 'query',
						property: 'is_licensed',
					},
				},
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: {
					minValue: 1,
					maxValue: 50,
				},
				default: 50,
				description: 'Max number of results to return',
				routing: {
					send: {
						type: 'query',
						property: 'limit',
					},
				},
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				typeOptions: {
					minValue: 1,
					maxValue: 100,
				},
				default: 1,
				description: 'Page number for pagination',
				routing: {
					send: {
						type: 'query',
						property: 'page',
					},
				},
			},
			{
				displayName: 'Publisher',
				name: 'publisher',
				type: 'string',
				default: '',
				description: 'Filter by publisher name',
				routing: {
					send: {
						type: 'query',
						property: 'publisher',
					},
				},
			},
			{
				displayName: 'Random Seed',
				name: 'random_seed',
				type: 'number',
				typeOptions: {
					minValue: -1,
					maxValue: 1,
				},
				default: undefined,
				description: 'Random seed for consistent random sorting (use with sort_by=random)',
				routing: {
					send: {
						type: 'query',
						property: 'random_seed',
					},
				},
			},
			{
				displayName: 'Rating Lower Bound',
				name: 'rating_lower',
				type: 'number',
				typeOptions: {
					minValue: 0,
					maxValue: 100,
				},
				default: undefined,
				description: 'Minimum rating (0-100)',
				routing: {
					send: {
						type: 'query',
						property: 'rating_lower',
					},
				},
			},
			{
				displayName: 'Rating Upper Bound',
				name: 'rating_upper',
				type: 'number',
				typeOptions: {
					minValue: 0,
					maxValue: 100,
				},
				default: undefined,
				description: 'Maximum rating (0-100)',
				routing: {
					send: {
						type: 'query',
						property: 'rating_upper',
					},
				},
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 'relevance_desc',
				description: 'How to sort the results',
				options: [
					{ name: 'Chapters (High to Low)', value: 'chapters_desc' },
					{ name: 'Chapters (Low to High)', value: 'chapters_asc' },
					{ name: 'Latest', value: 'latest' },
					{ name: 'Name (A-Z)', value: 'name_asc' },
					{ name: 'Name (Z-A)', value: 'name_desc' },
					{ name: 'Popularity (High to Low)', value: 'popularity_desc' },
					{ name: 'Popularity (Low to High)', value: 'popularity_asc' },
					{ name: 'Published Year (Newest First)', value: 'published_year_desc' },
					{ name: 'Published Year (Oldest First)', value: 'published_year_asc' },
					{ name: 'Random', value: 'random' },
					{ name: 'Relevance (High to Low)', value: 'relevance_desc' },
					{ name: 'Relevance (Low to High)', value: 'relevance_asc' },
					{ name: 'Score (High to Low)', value: 'score_desc' },
					{ name: 'Score (Low to High)', value: 'score_asc' },
					{ name: 'Volumes (High to Low)', value: 'volumes_desc' },
					{ name: 'Volumes (Low to High)', value: 'volumes_asc' },
				],
				routing: {
					send: {
						type: 'query',
						property: 'sort_by',
					},
				},
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'multiOptions',
				default: [],
				description: 'Filter by publication status',
				options: [
					{ name: 'Cancelled', value: 'cancelled' },
					{ name: 'Completed', value: 'completed' },
					{ name: 'Hiatus', value: 'hiatus' },
					{ name: 'Releasing', value: 'releasing' },
					{ name: 'Unknown', value: 'unknown' },
					{ name: 'Upcoming', value: 'upcoming' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('status')],
					},
				},
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'multiOptions',
				default: [],
				description: 'Filter by media type',
				options: [
					{ name: 'Manga', value: 'manga' },
					{ name: 'Manhua', value: 'manhua' },
					{ name: 'Manhwa', value: 'manhwa' },
					{ name: 'Novel', value: 'novel' },
					{ name: 'OEL', value: 'oel' },
					{ name: 'Other', value: 'other' },
				],
				routing: {
					send: {
						preSend: [multiOptionsToRepeatedParams('type')],
					},
				},
			},
			{
				displayName: 'With Boosts',
				name: 'with_boosts',
				type: 'boolean',
				default: true,
				description: 'Whether to include boosted results',
				routing: {
					send: {
						type: 'query',
						property: 'with_boosts',
					},
				},
			},
			{
				displayName: 'With Ignore Content Rating Count',
				name: 'with_ignore_content_rating_count',
				type: 'boolean',
				default: false,
				description: 'Whether to return count of results hidden due to content rating restrictions',
				routing: {
					send: {
						type: 'query',
						property: 'with_ignore_content_rating_count',
					},
				},
			},
			{
				displayName: 'Year Lower Bound',
				name: 'year_lower',
				type: 'number',
				default: undefined,
				description: 'Minimum publication year',
				routing: {
					send: {
						type: 'query',
						property: 'year_lower',
					},
				},
			},
			{
				displayName: 'Year Upper Bound',
				name: 'year_upper',
				type: 'number',
				default: undefined,
				description: 'Maximum publication year',
				routing: {
					send: {
						type: 'query',
						property: 'year_upper',
					},
				},
			},
		],
	},
];
